### ISSUE TITLE
Rework simulation tutorials

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tutorials#175]
At the moment we have high level sections that say "backwards simulations" and "forwards simulations", but a few sketched-out tutorials apply to both, e.g. "you don't need mutations", "combining forwards and backwards sims". In fact, even the proposed tutorial on []() . Moreover, we don't intend to include tutorials here that actually show you how to use the forward simulators, so the "forwards simulations" section is unlikely to be filled with much. Therefore, I suggest that a better layout would be:

```
- caption: Simulation
  chapters:
  - file: simulation_overview
  - file: no_mutations
  - file: completing-forward-sims
  - file: msprime
    sections:
    - file: demography
    - file: bottlenecks
    - file: introgression
  - file: forward_sims
```

Where `simulation_overview` is a small summary page making points such as the following:
* Why simulations are useful (e.g. exploring expectations in parameter space, ground truth for inference, ABC, etc.)
* The pros and cons of forwards vs backwards simulation
* Point out that forwards and backward simulations can be combined (link to specific tutorial)
* A few pointers for software packages that do simulation.
